### ISSUE TITLE
Tidy up Prometheus config

### ISSUE THREAD

**Issue by tomwilkie** [grafana/jsonnet-libs#160]
- [x] remove option to run as a deployment. (#156)
- [x] remove old non-sharded dashboard config map.
- [x] remove support for old mixin field names (`grafana_dashboards` vs `grafanaDashboards`) #234
- [x] scrape grafana metrics (#239)
- [x] stop running grafana as root (#240)
- [x] stop running prometheus, alertmanager etc as root (but keep them serving on port 80 if possible) (#244)
- [ ] get rid of the lib folder, put them all in the base folder like the rest of our modules.
- [x] move HA pair handling here.
- [ ] move the config fields into their respective files, and remove unused ones.
- [ ] audit and update node-exporter flags (we have ones left over from 0.16)
- [x] add silence link to alert template
- [x] make a file per-mixins' alerts, not one big file - makes diffing easier when order changes.

**Comment by beorn7** [comment]
I guess @cstyan and I can divide this among the two of us.

**Comment by malcolmholmes** [comment]
Grafana does not reload on yaml file changes, just json (i.e. dashboards). This catches users out as they expect dashboards and notification channels to reload but they dont.

The yaml configmaps should have hashes to trigger reloads to fix this.

**Comment by beorn7** [comment]
Note: We have solved the configmap layout in a different way, and tanka made diffing easy in yet another way.

**Comment by beorn7** [comment]
I think we can consider the config related tasks as done or obsolete. @malcolmholmes / @Duologic you did so much there, could you verify?

Which leaves us with node_exporter, which is indeed running in an ancient version. That upgrade with all the ramifications might be a good starter project for someone on the cloud-platform team?

**Comment by beorn7** [comment]
I take silence as a yes. Closing this, as I have created a separate issue for the node-exporter update, #527 .
